// <auto-generated />
using System;
using EveryDayBlog.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EveryDayBlog.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190724080503_AddingProffesion")]
    partial class AddingProffesion
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EveryDayBlog.Data.Models.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<DateTime>("CreatedOn");

                    b.Property<DateTime?>("DeletedOn");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("EveryDayBlog.Data.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("CountryCode");

                    b.Property<DateTime>("CreatedOn");

                    b.Property<DateTime?>("DeletedOn");

                    b.Property<string>("Description");

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50);

                    b.Property<int?>("ImageId");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("LastName")
                        .HasMaxLength(50);

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("Profession");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("CountryCode");

                    b.HasIndex("ImageId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("EveryDayBlog.Data.Models.Country", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Code");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Code = "AF",
                            Name = "Afghanistan"
                        },
                        new
                        {
                            Code = "AX",
                            Name = "Åland Islands"
                        },
                        new
                        {
                            Code = "AL",
                            Name = "Albania"
                        },
                        new
                        {
                            Code = "DZ",
                            Name = "Algeria"
                        },
                        new
                        {
                            Code = "AS",
                            Name = "American Samoa"
                        },
                        new
                        {
                            Code = "AD",
                            Name = "AndorrA"
                        },
                        new
                        {
                            Code = "AO",
                            Name = "Angola"
                        },
                        new
                        {
                            Code = "AI",
                            Name = "Anguilla"
                        },
                        new
                        {
                            Code = "AQ",
                            Name = "Antarctica"
                        },
                        new
                        {
                            Code = "AG",
                            Name = "Antigua and Barbuda"
                        },
                        new
                        {
                            Code = "AR",
                            Name = "Argentina"
                        },
                        new
                        {
                            Code = "AM",
                            Name = "Armenia"
                        },
                        new
                        {
                            Code = "AW",
                            Name = "Aruba"
                        },
                        new
                        {
                            Code = "AU",
                            Name = "Australia"
                        },
                        new
                        {
                            Code = "AT",
                            Name = "Austria"
                        },
                        new
                        {
                            Code = "AZ",
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            Code = "BS",
                            Name = "Bahamas"
                        },
                        new
                        {
                            Code = "BH",
                            Name = "Bahrain"
                        },
                        new
                        {
                            Code = "BD",
                            Name = "Bangladesh"
                        },
                        new
                        {
                            Code = "BB",
                            Name = "Barbados"
                        },
                        new
                        {
                            Code = "BY",
                            Name = "Belarus"
                        },
                        new
                        {
                            Code = "BE",
                            Name = "Belgium"
                        },
                        new
                        {
                            Code = "BZ",
                            Name = "Belize"
                        },
                        new
                        {
                            Code = "BJ",
                            Name = "Benin"
                        },
                        new
                        {
                            Code = "BM",
                            Name = "Bermuda"
                        },
                        new
                        {
                            Code = "BT",
                            Name = "Bhutan"
                        },
                        new
                        {
                            Code = "BO",
                            Name = "Bolivia"
                        },
                        new
                        {
                            Code = "BA",
                            Name = "Bosnia and Herzegovina"
                        },
                        new
                        {
                            Code = "BW",
                            Name = "Botswana"
                        },
                        new
                        {
                            Code = "BV",
                            Name = "Bouvet Island"
                        },
                        new
                        {
                            Code = "BR",
                            Name = "Brazil"
                        },
                        new
                        {
                            Code = "IO",
                            Name = "British Indian Ocean Territory"
                        },
                        new
                        {
                            Code = "BN",
                            Name = "Brunei Darussalam"
                        },
                        new
                        {
                            Code = "BG",
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Code = "BF",
                            Name = "Burkina Faso"
                        },
                        new
                        {
                            Code = "BI",
                            Name = "Burundi"
                        },
                        new
                        {
                            Code = "KH",
                            Name = "Cambodia"
                        },
                        new
                        {
                            Code = "CM",
                            Name = "Cameroon"
                        },
                        new
                        {
                            Code = "CA",
                            Name = "Canada"
                        },
                        new
                        {
                            Code = "CV",
                            Name = "Cape Verde"
                        },
                        new
                        {
                            Code = "KY",
                            Name = "Cayman Islands"
                        },
                        new
                        {
                            Code = "CF",
                            Name = "Central African Republic"
                        },
                        new
                        {
                            Code = "TD",
                            Name = "Chad"
                        },
                        new
                        {
                            Code = "CL",
                            Name = "Chile"
                        },
                        new
                        {
                            Code = "CN",
                            Name = "China"
                        },
                        new
                        {
                            Code = "CX",
                            Name = "Christmas Island"
                        },
                        new
                        {
                            Code = "CC",
                            Name = "Cocos (Keeling) Islands"
                        },
                        new
                        {
                            Code = "CO",
                            Name = "Colombia"
                        },
                        new
                        {
                            Code = "KM",
                            Name = "Comoros"
                        },
                        new
                        {
                            Code = "CG",
                            Name = "Congo"
                        },
                        new
                        {
                            Code = "CD",
                            Name = "Congo, The Democratic Republic of the"
                        },
                        new
                        {
                            Code = "CK",
                            Name = "Cook Islands"
                        },
                        new
                        {
                            Code = "CR",
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Code = "CI",
                            Name = "Cote D'Ivoire"
                        },
                        new
                        {
                            Code = "HR",
                            Name = "Croatia"
                        },
                        new
                        {
                            Code = "CU",
                            Name = "Cuba"
                        },
                        new
                        {
                            Code = "CY",
                            Name = "Cyprus"
                        },
                        new
                        {
                            Code = "CZ",
                            Name = "Czech Republic"
                        },
                        new
                        {
                            Code = "DK",
                            Name = "Denmark"
                        },
                        new
                        {
                            Code = "DJ",
                            Name = "Djibouti"
                        },
                        new
                        {
                            Code = "DM",
                            Name = "Dominica"
                        },
                        new
                        {
                            Code = "DO",
                            Name = "Dominican Republic"
                        },
                        new
                        {
                            Code = "EC",
                            Name = "Ecuador"
                        },
                        new
                        {
                            Code = "EG",
                            Name = "Egypt"
                        },
                        new
                        {
                            Code = "SV",
                            Name = "El Salvador"
                        },
                        new
                        {
                            Code = "GQ",
                            Name = "Equatorial Guinea"
                        },
                        new
                        {
                            Code = "ER",
                            Name = "Eritrea"
                        },
                        new
                        {
                            Code = "EE",
                            Name = "Estonia"
                        },
                        new
                        {
                            Code = "ET",
                            Name = "Ethiopia"
                        },
                        new
                        {
                            Code = "FK",
                            Name = "Falkland Islands (Malvinas)"
                        },
                        new
                        {
                            Code = "FO",
                            Name = "Faroe Islands"
                        },
                        new
                        {
                            Code = "FJ",
                            Name = "Fiji"
                        },
                        new
                        {
                            Code = "FI",
                            Name = "Finland"
                        },
                        new
                        {
                            Code = "FR",
                            Name = "France"
                        },
                        new
                        {
                            Code = "GF",
                            Name = "French Guiana"
                        },
                        new
                        {
                            Code = "PF",
                            Name = "French Polynesia"
                        },
                        new
                        {
                            Code = "TF",
                            Name = "French Southern Territories"
                        },
                        new
                        {
                            Code = "GA",
                            Name = "Gabon"
                        },
                        new
                        {
                            Code = "GM",
                            Name = "Gambia"
                        },
                        new
                        {
                            Code = "GE",
                            Name = "Georgia"
                        },
                        new
                        {
                            Code = "DE",
                            Name = "Germany"
                        },
                        new
                        {
                            Code = "GH",
                            Name = "Ghana"
                        },
                        new
                        {
                            Code = "GI",
                            Name = "Gibraltar"
                        },
                        new
                        {
                            Code = "GR",
                            Name = "Greece"
                        },
                        new
                        {
                            Code = "GL",
                            Name = "Greenland"
                        },
                        new
                        {
                            Code = "GD",
                            Name = "Grenada"
                        },
                        new
                        {
                            Code = "GP",
                            Name = "Guadeloupe"
                        },
                        new
                        {
                            Code = "GU",
                            Name = "Guam"
                        },
                        new
                        {
                            Code = "GT",
                            Name = "Guatemala"
                        },
                        new
                        {
                            Code = "GG",
                            Name = "Guernsey"
                        },
                        new
                        {
                            Code = "GN",
                            Name = "Guinea"
                        },
                        new
                        {
                            Code = "GW",
                            Name = "Guinea-Bissau"
                        },
                        new
                        {
                            Code = "GY",
                            Name = "Guyana"
                        },
                        new
                        {
                            Code = "HT",
                            Name = "Haiti"
                        },
                        new
                        {
                            Code = "HM",
                            Name = "Heard Island and Mcdonald Islands"
                        },
                        new
                        {
                            Code = "VA",
                            Name = "Holy See (Vatican City State)"
                        },
                        new
                        {
                            Code = "HN",
                            Name = "Honduras"
                        },
                        new
                        {
                            Code = "HK",
                            Name = "Hong Kong"
                        },
                        new
                        {
                            Code = "HU",
                            Name = "Hungary"
                        },
                        new
                        {
                            Code = "IS",
                            Name = "Iceland"
                        },
                        new
                        {
                            Code = "IN",
                            Name = "India"
                        },
                        new
                        {
                            Code = "ID",
                            Name = "Indonesia"
                        },
                        new
                        {
                            Code = "IR",
                            Name = "Iran, Islamic Republic Of"
                        },
                        new
                        {
                            Code = "IQ",
                            Name = "Iraq"
                        },
                        new
                        {
                            Code = "IE",
                            Name = "Ireland"
                        },
                        new
                        {
                            Code = "IM",
                            Name = "Isle of Man"
                        },
                        new
                        {
                            Code = "IL",
                            Name = "Israel"
                        },
                        new
                        {
                            Code = "IT",
                            Name = "Italy"
                        },
                        new
                        {
                            Code = "JM",
                            Name = "Jamaica"
                        },
                        new
                        {
                            Code = "JP",
                            Name = "Japan"
                        },
                        new
                        {
                            Code = "JE",
                            Name = "Jersey"
                        },
                        new
                        {
                            Code = "JO",
                            Name = "Jordan"
                        },
                        new
                        {
                            Code = "KZ",
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            Code = "KE",
                            Name = "Kenya"
                        },
                        new
                        {
                            Code = "KI",
                            Name = "Kiribati"
                        },
                        new
                        {
                            Code = "KP",
                            Name = "Korea, Democratic People'S Republic of"
                        },
                        new
                        {
                            Code = "KR",
                            Name = "Korea, Republic of"
                        },
                        new
                        {
                            Code = "KW",
                            Name = "Kuwait"
                        },
                        new
                        {
                            Code = "KG",
                            Name = "Kyrgyzstan"
                        },
                        new
                        {
                            Code = "LA",
                            Name = "Lao People'S Democratic Republic"
                        },
                        new
                        {
                            Code = "LV",
                            Name = "Latvia"
                        },
                        new
                        {
                            Code = "LB",
                            Name = "Lebanon"
                        },
                        new
                        {
                            Code = "LS",
                            Name = "Lesotho"
                        },
                        new
                        {
                            Code = "LR",
                            Name = "Liberia"
                        },
                        new
                        {
                            Code = "LY",
                            Name = "Libyan Arab Jamahiriya"
                        },
                        new
                        {
                            Code = "LI",
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            Code = "LT",
                            Name = "Lithuania"
                        },
                        new
                        {
                            Code = "LU",
                            Name = "Luxembourg"
                        },
                        new
                        {
                            Code = "MO",
                            Name = "Macao"
                        },
                        new
                        {
                            Code = "MK",
                            Name = "Macedonia, The Former Yugoslav Republic of"
                        },
                        new
                        {
                            Code = "MG",
                            Name = "Madagascar"
                        },
                        new
                        {
                            Code = "MW",
                            Name = "Malawi"
                        },
                        new
                        {
                            Code = "MY",
                            Name = "Malaysia"
                        },
                        new
                        {
                            Code = "MV",
                            Name = "Maldives"
                        },
                        new
                        {
                            Code = "ML",
                            Name = "Mali"
                        },
                        new
                        {
                            Code = "MT",
                            Name = "Malta"
                        },
                        new
                        {
                            Code = "MH",
                            Name = "Marshall Islands"
                        },
                        new
                        {
                            Code = "MQ",
                            Name = "Martinique"
                        },
                        new
                        {
                            Code = "MR",
                            Name = "Mauritania"
                        },
                        new
                        {
                            Code = "MU",
                            Name = "Mauritius"
                        },
                        new
                        {
                            Code = "YT",
                            Name = "Mayotte"
                        },
                        new
                        {
                            Code = "MX",
                            Name = "Mexico"
                        },
                        new
                        {
                            Code = "FM",
                            Name = "Micronesia, Federated States of"
                        },
                        new
                        {
                            Code = "MD",
                            Name = "Moldova, Republic of"
                        },
                        new
                        {
                            Code = "MC",
                            Name = "Monaco"
                        },
                        new
                        {
                            Code = "MN",
                            Name = "Mongolia"
                        },
                        new
                        {
                            Code = "MS",
                            Name = "Montserrat"
                        },
                        new
                        {
                            Code = "MA",
                            Name = "Morocco"
                        },
                        new
                        {
                            Code = "MZ",
                            Name = "Mozambique"
                        },
                        new
                        {
                            Code = "MM",
                            Name = "Myanmar"
                        },
                        new
                        {
                            Code = "NA",
                            Name = "Namibia"
                        },
                        new
                        {
                            Code = "NR",
                            Name = "Nauru"
                        },
                        new
                        {
                            Code = "NP",
                            Name = "Nepal"
                        },
                        new
                        {
                            Code = "NL",
                            Name = "Netherlands"
                        },
                        new
                        {
                            Code = "AN",
                            Name = "Netherlands Antilles"
                        },
                        new
                        {
                            Code = "NC",
                            Name = "New Caledonia"
                        },
                        new
                        {
                            Code = "NZ",
                            Name = "New Zealand"
                        },
                        new
                        {
                            Code = "NI",
                            Name = "Nicaragua"
                        },
                        new
                        {
                            Code = "NE",
                            Name = "Niger"
                        },
                        new
                        {
                            Code = "NG",
                            Name = "Nigeria"
                        },
                        new
                        {
                            Code = "NU",
                            Name = "Niue"
                        },
                        new
                        {
                            Code = "NF",
                            Name = "Norfolk Island"
                        },
                        new
                        {
                            Code = "MP",
                            Name = "Northern Mariana Islands"
                        },
                        new
                        {
                            Code = "NO",
                            Name = "Norway"
                        },
                        new
                        {
                            Code = "OM",
                            Name = "Oman"
                        },
                        new
                        {
                            Code = "PK",
                            Name = "Pakistan"
                        },
                        new
                        {
                            Code = "PW",
                            Name = "Palau"
                        },
                        new
                        {
                            Code = "PS",
                            Name = "Palestinian Territory, Occupied"
                        },
                        new
                        {
                            Code = "PA",
                            Name = "Panama"
                        },
                        new
                        {
                            Code = "PG",
                            Name = "Papua New Guinea"
                        },
                        new
                        {
                            Code = "PY",
                            Name = "Paraguay"
                        },
                        new
                        {
                            Code = "PE",
                            Name = "Peru"
                        },
                        new
                        {
                            Code = "PH",
                            Name = "Philippines"
                        },
                        new
                        {
                            Code = "PN",
                            Name = "Pitcairn"
                        },
                        new
                        {
                            Code = "PL",
                            Name = "Poland"
                        },
                        new
                        {
                            Code = "PT",
                            Name = "Portugal"
                        },
                        new
                        {
                            Code = "PR",
                            Name = "Puerto Rico"
                        },
                        new
                        {
                            Code = "QA",
                            Name = "Qatar"
                        },
                        new
                        {
                            Code = "RE",
                            Name = "Reunion"
                        },
                        new
                        {
                            Code = "RO",
                            Name = "Romania"
                        },
                        new
                        {
                            Code = "RU",
                            Name = "Russian Federation"
                        },
                        new
                        {
                            Code = "RW",
                            Name = "RWANDA"
                        },
                        new
                        {
                            Code = "SH",
                            Name = "Saint Helena"
                        },
                        new
                        {
                            Code = "KN",
                            Name = "Saint Kitts and Nevis"
                        },
                        new
                        {
                            Code = "LC",
                            Name = "Saint Lucia"
                        },
                        new
                        {
                            Code = "PM",
                            Name = "Saint Pierre and Miquelon"
                        },
                        new
                        {
                            Code = "VC",
                            Name = "Saint Vincent and the Grenadines"
                        },
                        new
                        {
                            Code = "WS",
                            Name = "Samoa"
                        },
                        new
                        {
                            Code = "SM",
                            Name = "San Marino"
                        },
                        new
                        {
                            Code = "ST",
                            Name = "Sao Tome and Principe"
                        },
                        new
                        {
                            Code = "SA",
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            Code = "SN",
                            Name = "Senegal"
                        },
                        new
                        {
                            Code = "CS",
                            Name = "Serbia and Montenegro"
                        },
                        new
                        {
                            Code = "SC",
                            Name = "Seychelles"
                        },
                        new
                        {
                            Code = "SL",
                            Name = "Sierra Leone"
                        },
                        new
                        {
                            Code = "SG",
                            Name = "Singapore"
                        },
                        new
                        {
                            Code = "SK",
                            Name = "Slovakia"
                        },
                        new
                        {
                            Code = "SI",
                            Name = "Slovenia"
                        },
                        new
                        {
                            Code = "SB",
                            Name = "Solomon Islands"
                        },
                        new
                        {
                            Code = "SO",
                            Name = "Somalia"
                        },
                        new
                        {
                            Code = "ZA",
                            Name = "South Africa"
                        },
                        new
                        {
                            Code = "GS",
                            Name = "South Georgia and the South Sandwich Islands"
                        },
                        new
                        {
                            Code = "ES",
                            Name = "Spain"
                        },
                        new
                        {
                            Code = "LK",
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            Code = "SD",
                            Name = "Sudan"
                        },
                        new
                        {
                            Code = "SR",
                            Name = "Suriname"
                        },
                        new
                        {
                            Code = "SJ",
                            Name = "Svalbard and Jan Mayen"
                        },
                        new
                        {
                            Code = "SZ",
                            Name = "Swaziland"
                        },
                        new
                        {
                            Code = "SE",
                            Name = "Sweden"
                        },
                        new
                        {
                            Code = "CH",
                            Name = "Switzerland"
                        },
                        new
                        {
                            Code = "SY",
                            Name = "Syrian Arab Republic"
                        },
                        new
                        {
                            Code = "TW",
                            Name = "Taiwan, Province of China"
                        },
                        new
                        {
                            Code = "TJ",
                            Name = "Tajikistan"
                        },
                        new
                        {
                            Code = "TZ",
                            Name = "Tanzania, United Republic of"
                        },
                        new
                        {
                            Code = "TH",
                            Name = "Thailand"
                        },
                        new
                        {
                            Code = "TL",
                            Name = "Timor-Leste"
                        },
                        new
                        {
                            Code = "TG",
                            Name = "Togo"
                        },
                        new
                        {
                            Code = "TK",
                            Name = "Tokelau"
                        },
                        new
                        {
                            Code = "TO",
                            Name = "Tonga"
                        },
                        new
                        {
                            Code = "TT",
                            Name = "Trinidad and Tobago"
                        },
                        new
                        {
                            Code = "TN",
                            Name = "Tunisia"
                        },
                        new
                        {
                            Code = "TR",
                            Name = "Turkey"
                        },
                        new
                        {
                            Code = "TM",
                            Name = "Turkmenistan"
                        },
                        new
                        {
                            Code = "TC",
                            Name = "Turks and Caicos Islands"
                        },
                        new
                        {
                            Code = "TV",
                            Name = "Tuvalu"
                        },
                        new
                        {
                            Code = "UG",
                            Name = "Uganda"
                        },
                        new
                        {
                            Code = "UA",
                            Name = "Ukraine"
                        },
                        new
                        {
                            Code = "AE",
                            Name = "United Arab Emirates"
                        },
                        new
                        {
                            Code = "GB",
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Code = "US",
                            Name = "United States"
                        },
                        new
                        {
                            Code = "UM",
                            Name = "United States Minor Outlying Islands"
                        },
                        new
                        {
                            Code = "UY",
                            Name = "Uruguay"
                        },
                        new
                        {
                            Code = "UZ",
                            Name = "Uzbekistan"
                        },
                        new
                        {
                            Code = "VU",
                            Name = "Vanuatu"
                        },
                        new
                        {
                            Code = "VE",
                            Name = "Venezuela"
                        },
                        new
                        {
                            Code = "VN",
                            Name = "Viet Nam"
                        },
                        new
                        {
                            Code = "VG",
                            Name = "Virgin Islands, British"
                        },
                        new
                        {
                            Code = "VI",
                            Name = "Virgin Islands, U.S."
                        },
                        new
                        {
                            Code = "WF",
                            Name = "Wallis and Futuna"
                        },
                        new
                        {
                            Code = "EH",
                            Name = "Western Sahara"
                        },
                        new
                        {
                            Code = "YE",
                            Name = "Yemen"
                        },
                        new
                        {
                            Code = "ZM",
                            Name = "Zambia"
                        },
                        new
                        {
                            Code = "ZW",
                            Name = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("EveryDayBlog.Data.Models.Image", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CloudUrl");

                    b.Property<string>("ContentType")
                        .IsRequired();

                    b.Property<DateTime>("CreatedOn");

                    b.Property<DateTime?>("DeletedOn");

                    b.Property<string>("ImagePath");

                    b.Property<string>("ImageTitle");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("ModifiedOn");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("EveryDayBlog.Data.Models.PageHeader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn");

                    b.Property<DateTime?>("DeletedOn");

                    b.Property<int?>("ImageId");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<string>("PageIndicator")
                        .IsRequired();

                    b.Property<string>("SubTitle")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.HasIndex("IsDeleted");

                    b.ToTable("PagesHeaders");
                });

            modelBuilder.Entity("EveryDayBlog.Data.Models.Paragraph", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn");

                    b.Property<DateTime?>("DeletedOn");

                    b.Property<int?>("ImageId");

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("MainText")
                        .IsRequired();

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<int?>("SectionId");

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("SectionId");

                    b.ToTable("Paragraphs");
                });

            modelBuilder.Entity("EveryDayBlog.Data.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn");

                    b.Property<DateTime?>("DeletedOn");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<int>("PageHeaderId");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("PageHeaderId");

                    b.HasIndex("UserId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("EveryDayBlog.Data.Models.Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn");

                    b.Property<DateTime?>("DeletedOn");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<int?>("PostId");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("PostId");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("EveryDayBlog.Data.Models.Setting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedOn");

                    b.Property<DateTime?>("DeletedOn");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("ModifiedOn");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("EveryDayBlog.Data.Models.ApplicationUser", b =>
                {
                    b.HasOne("EveryDayBlog.Data.Models.Country", "Country")
                        .WithMany("Users")
                        .HasForeignKey("CountryCode")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EveryDayBlog.Data.Models.Image", "Image")
                        .WithMany("Users")
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("EveryDayBlog.Data.Models.PageHeader", b =>
                {
                    b.HasOne("EveryDayBlog.Data.Models.Image", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId");
                });

            modelBuilder.Entity("EveryDayBlog.Data.Models.Paragraph", b =>
                {
                    b.HasOne("EveryDayBlog.Data.Models.Image", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId");

                    b.HasOne("EveryDayBlog.Data.Models.Section")
                        .WithMany("Paragraphs")
                        .HasForeignKey("SectionId");
                });

            modelBuilder.Entity("EveryDayBlog.Data.Models.Post", b =>
                {
                    b.HasOne("EveryDayBlog.Data.Models.PageHeader", "PageHeader")
                        .WithMany()
                        .HasForeignKey("PageHeaderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EveryDayBlog.Data.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("EveryDayBlog.Data.Models.Section", b =>
                {
                    b.HasOne("EveryDayBlog.Data.Models.Post")
                        .WithMany("Sections")
                        .HasForeignKey("PostId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("EveryDayBlog.Data.Models.ApplicationRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("EveryDayBlog.Data.Models.ApplicationUser")
                        .WithMany("Claims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("EveryDayBlog.Data.Models.ApplicationUser")
                        .WithMany("Logins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("EveryDayBlog.Data.Models.ApplicationRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EveryDayBlog.Data.Models.ApplicationUser")
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("EveryDayBlog.Data.Models.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
